"""Regression checks for Tauri command registration and ACL wiring."""

from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TAURI_ROOT = ROOT / "desktop" / "src-tauri"


def _invoke_handler_commands() -> set[str]:
    source = (TAURI_ROOT / "src" / "main.rs").read_text(encoding="utf-8")
    match = re.search(
        r"\.invoke_handler\(tauri::generate_handler!\[(.*?)\]\)",
        source,
        flags=re.DOTALL,
    )
    assert match is not None, "Could not find the Tauri invoke handler"
    entries = re.findall(r"(?m)^\s*([A-Za-z_][A-Za-z0-9_:]*)\s*,", match[1])
    return {entry.rsplit("::", maxsplit=1)[-1] for entry in entries}


def _build_manifest_commands() -> set[str]:
    source = (TAURI_ROOT / "build.rs").read_text(encoding="utf-8")
    match = re.search(
        r"AppManifest::new\(\)\.commands\(&\[(.*?)\]\)", source, re.DOTALL
    )
    assert match is not None, "Could not find the Tauri build command manifest"
    return set(re.findall(r'"([a-z][a-z0-9_]*)"', match[1]))


def test_invoke_handler_and_build_manifest_stay_in_sync() -> None:
    """Every runtime command must be known while ACL files are generated."""

    assert _build_manifest_commands() == _invoke_handler_commands()


def test_invoke_commands_have_generated_permissions_and_capabilities() -> None:
    """Prevent runtime `not allowed` failures from incomplete ACL wiring."""

    capability = json.loads(
        (TAURI_ROOT / "capabilities" / "default.json").read_text(encoding="utf-8")
    )
    enabled_permissions = set(capability["permissions"])
    permission_root = TAURI_ROOT / "permissions" / "autogenerated"

    for command in sorted(_invoke_handler_commands()):
        permission_id = f"allow-{command.replace('_', '-')}"
        assert permission_id in enabled_permissions, (
            f"{command} is registered but {permission_id} is missing from "
            "capabilities/default.json"
        )

        permission_path = permission_root / f"{command}.toml"
        assert permission_path.is_file(), (
            f"{command} is missing its generated permission file; add it to "
            "the AppManifest command list in build.rs and rebuild Tauri"
        )
        document = tomllib.loads(permission_path.read_text(encoding="utf-8"))
        allow_commands = {
            allowed
            for permission in document.get("permission", [])
            if permission.get("identifier") == permission_id
            for allowed in permission.get("commands", {}).get("allow", [])
        }
        assert command in allow_commands
